/*
 * botlib_port.h — the parts of the build environment that have NO counterpart
 * in Mr. Elusive's 1999 sources.
 *
 * Everything here exists only because we compile 32-bit MSVC6 source for a
 * 64-bit, POSIX toolchain.  It is kept apart from the reconstruction so the
 * line between "restored" and "scaffolding" is visible at a glance:
 *
 *   - the system #include set (the original .c files each included what they
 *     needed; we cannot know which, so one common set stands in)
 *   - shims for MSVC CRT names that POSIX spells differently
 *   - SHIDWORD, an IDA spelling for the high dword of a 64-bit value
 *   - the 64-bit side-band GATE.  Its per-struct accessor macros unavoidably
 *     live next to the structures they wrap, in botlib_local.h.
 *   - P()/FE()/FE_END, our spelling of the structdef field tables recovered
 *     from .data
 *
 * Nothing in this file corresponds to anything in the shipped DLL.
 */
#ifndef BOTLIB_PORT_H
#define BOTLIB_PORT_H

/* The IDA/Win32 spellings below guard on Q_SHARED_H and BOTLIB_H (vec3_t and
 * qboolean are defined by whichever of the two got there first), so those
 * headers have to be in scope before them -- gladiator.dll.h, where this
 * block came from, was always included after both. */
#include "../game/q_shared.h"
/* q_shared.h's VectorNegate is a 2-arg macro; botlib has a 1-arg in-place
 * VectorNegate() at 0x10043540.  Drop the macro so the function stays callable. */
#undef VectorNegate
#include "../game/botlib.h"

/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'gladiator.dll'
*/


#include <stddef.h>   /* wchar_t, offsetof, size_t */

#ifndef _MSC_VER


#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long
#endif

/* _iobuf/FILE are provided by <stdio.h> which must be included before this header. */

/* MSVC calling conventions — no-ops on non-Windows targets.  On MinGW these
 * are built-in GCC keywords: do NOT redefine them, or the attribute is
 * silently discarded and GetBotAPI breaks (game.dll calls it __stdcall). */
#if !defined(_MSC_VER) && !defined(_WIN32)
#ifndef __cdecl
#define __cdecl
#endif
#ifndef __stdcall
#define __stdcall
#endif
#ifndef __fastcall
#define __fastcall
#endif
#endif

/* Types required by MSVC exception-handling structs below,
   not otherwise defined in this header. */
typedef void *PVOID;
struct _EXCEPTION_RECORD;
struct _CONTEXT;
struct _EXCEPTION_POINTERS {
  struct _EXCEPTION_RECORD *ExceptionRecord;
  struct _CONTEXT           *ContextRecord;
};
typedef struct _EXCEPTION_POINTERS EXCEPTION_POINTERS;

/* 1 */
struct _SCOPETABLE_ENTRY
{
  int EnclosingLevel;
  void *FilterFunc;
  void *HandlerFunc;
};

/* 2 */
typedef struct _SCOPETABLE_ENTRY *PSCOPETABLE_ENTRY;

/* 8 */
typedef unsigned int DWORD;
typedef unsigned int _DWORD;

/* IDA Pro type aliases */
typedef unsigned char  _BYTE;
typedef unsigned short _WORD;
typedef unsigned int   _UNKNOWN;  /* IDA placeholder for unresolved 4-byte types */

/* Windows types not in the standard headers */
typedef void        *HGLOBAL;
typedef void        *HMODULE;
typedef void        *FARPROC;
typedef const char  *LPCSTR;

/* IDA Pro bit-extraction macros — reinterpret the bit pattern at a byte
   offset, matching MSVC's partial-register reads. */
#define LOBYTE(x)    (*(unsigned char *)&(x))
#define HIBYTE(x)    (*((unsigned char *)&(x) + 1))
#define BYTE1(x)     (*((unsigned char *)&(x) + 1))   /* alias for HIBYTE */
#define LOWORD(x)    (*(unsigned short *)&(x))
#define HIWORD(x)    (*((unsigned short *)&(x) + 1))
#define LODWORD(x)   (*(unsigned int *)&(x))
#define HIDWORD(x)   (*((int *)&(x) + 1))            /* signed: needed for IDA's `(HIDWORD(v) ^ v) - HIDWORD(v)` abs idiom on 64-bit */
#define SLODWORD(x)  (*(int *)&(x))                   /* signed variant */
#define SLOBYTE(x)   (*(signed char *)&(x))
#define BYTE2(x)     (*((unsigned char *)&(x) + 2))
/* COERCE_FLOAT: reinterpret an int's bits as a float.  An inline function
   (union type-punning) so it works on rvalues, unlike the & form. */
#if defined(_MSC_VER) && _MSC_VER < 1900
#define inline __inline
#endif
static inline float COERCE_FLOAT(int _x) { union { int i; float f; } _u; _u.i = _x; return _u.f; }

/* 3 */
struct _EH3_EXCEPTION_REGISTRATION
{
  struct _EH3_EXCEPTION_REGISTRATION *Next;
  PVOID ExceptionHandler;
  PSCOPETABLE_ENTRY ScopeTable;
  DWORD TryLevel;
};

/* 4 */
typedef struct _EH3_EXCEPTION_REGISTRATION EH3_EXCEPTION_REGISTRATION;

/* 5 */
typedef struct _EH3_EXCEPTION_REGISTRATION *PEH3_EXCEPTION_REGISTRATION;

/* 6 */
struct CPPEH_RECORD
{
  DWORD old_esp;
  EXCEPTION_POINTERS *exc_ptr;
  struct _EH3_EXCEPTION_REGISTRATION registration;
};

/* 7 */
struct _FILETIME
{
  DWORD dwLowDateTime;
  DWORD dwHighDateTime;
};

/* 11 */
typedef char CHAR;

/* 10 */
typedef CHAR *LPSTR;

/* 12 */
typedef unsigned __int16 WORD;

/* 14 */
typedef unsigned __int8 BYTE;

/* 13 */
typedef BYTE *LPBYTE;

/* 15 */
typedef void *HANDLE;

/* 9 */
struct _STARTUPINFOA
{
  DWORD cb;
  LPSTR lpReserved;
  LPSTR lpDesktop;
  LPSTR lpTitle;
  DWORD dwX;
  DWORD dwY;
  DWORD dwXSize;
  DWORD dwYSize;
  DWORD dwXCountChars;
  DWORD dwYCountChars;
  DWORD dwFillAttribute;
  DWORD dwFlags;
  WORD wShowWindow;
  WORD cbReserved2;
  LPBYTE lpReserved2;
  HANDLE hStdInput;
  HANDLE hStdOutput;
  HANDLE hStdError;
};

/* 17 */
typedef void *LPVOID;

/* 18 */
typedef int BOOL;
#ifndef Q_SHARED_H  /* q_shared.h defines qboolean as an enum — skip our int alias when present */
typedef int qboolean;  /* Q3-style boolean; matches game/botlib.h `typedef int qboolean` */
#endif

/* 16 */
struct _SECURITY_ATTRIBUTES
{
  DWORD nLength;
  LPVOID lpSecurityDescriptor;
  BOOL bInheritHandle;
};

/* 20 */
typedef unsigned int UINT;

/* 19 */
struct _cpinfo
{
  UINT MaxCharSize;
  BYTE DefaultChar[2];
  BYTE LeadByte[12];
};

/* 21 */
struct _OSVERSIONINFOA
{
  DWORD dwOSVersionInfoSize;
  DWORD dwMajorVersion;
  DWORD dwMinorVersion;
  DWORD dwBuildNumber;
  DWORD dwPlatformId;
  CHAR szCSDVersion[128];
};

/* 23 */
typedef int LONG;

/* 25 */
/* wchar_t: defined by <stddef.h> on POSIX as unsigned int (32-bit).
 * Only provide the Windows 16-bit alias on Windows targets. */
#if defined(_WIN32) && !defined(__cplusplus)
typedef unsigned __int16 wchar_t;
#endif

/* 24 */
typedef wchar_t WCHAR;

/* 27 */
struct _SYSTEMTIME
{
  WORD wYear;
  WORD wMonth;
  WORD wDayOfWeek;
  WORD wDay;
  WORD wHour;
  WORD wMinute;
  WORD wSecond;
  WORD wMilliseconds;
};

/* 26 */
typedef struct _SYSTEMTIME SYSTEMTIME;

/* 22 */
struct _TIME_ZONE_INFORMATION
{
  LONG Bias;
  WCHAR StandardName[32];
  SYSTEMTIME StandardDate;
  LONG StandardBias;
  WCHAR DaylightName[32];
  SYSTEMTIME DaylightDate;
  LONG DaylightBias;
};

/* 28 */
struct _PROCESS_INFORMATION
{
  HANDLE hProcess;
  HANDLE hThread;
  DWORD dwProcessId;
  DWORD dwThreadId;
};

/* 29, 30 — _iobuf/FILE: provided by <stdio.h>, included before this header. */

/* vec3_t — guarded because game/botlib.h and q_shared.h both define it. */
#if !defined(BOTLIB_H) && !defined(Q_SHARED_H)
typedef float vec3_t[3];
#endif

#include <math.h>
#include <stdarg.h>
#include <stddef.h>    /* offsetof, size_t */
#include <stdint.h>    /* intptr_t */
#include <stdio.h>     /* file I/O, sprintf, sscanf */
#include <string.h>    /* string and memory ops */
#include <stdlib.h>    /* malloc, atoi, rand, abs */
#include <ctype.h>     /* toupper */
#include <errno.h>     /* errno */
#include <time.h>      /* time(), ctime() */
#include <unistd.h>    /* access(), chdir(), getcwd() */


/* signed high-word/dword accessors */
#define SHIDWORD(x)  (*((int *)&(x) + 1))

/* Stubs for the statically-linked MSVC CRT helpers the bot code still calls. */
static size_t fread_locked(void *buf, size_t sz, size_t n, FILE *f) { return fread(buf, sz, n, f); }
#ifdef _WIN32
/* Windows-only winbspc/zip subsystem (sub_1000E140/sub_1000E430, sub_10041FF0);
 * the Linux botlib has neither a process-spawn nor a chdir-for-bspc path. */
static int    remove_file(const char *path) { return remove(path); }
static int    getcwd_locked(char *buf, int size) { return getcwd(buf, size) ? 0 : -1; }
static intptr_t SpawnProcess(int mode, char *file, char *args, char *cmd, char *addargs) { (void)mode; (void)file; (void)args; (void)cmd; (void)addargs; return -1; }
/* _access is provided by MinGW's <io.h>; _chdir by <direct.h> — use POSIX wrappers */
static int    _chdir(const char *path) { return chdir(path); }
#endif /* _WIN32 */

#ifndef _WIN32
/* POSIX equivalents for the Windows CRT functions used below. */
#include <strings.h>    /* strcasecmp */
#define _strcmpi   strcasecmp
#define _access    access
typedef int __time32_t;   /* Windows 32-bit time type; int is 32-bit on all targets */
#endif

/* AI node function pointer type (used for BotAINode side-band table) */
typedef int (*ai_node_fn_t)(struct bot_state_s *bs);

/* ------------------------------------------------------------------------
 * Side-band gate.
 *
 * Every "pointer slot" in bot_state_t / bot_chatstate_t / aas_entity_t is a
 * 4-byte int field holding a pointer bit-pattern.  On 64-bit those slots are
 * too narrow, so each is mirrored into a parallel heap array (the side-band)
 * reached through helper macros (BotCharacter, BotAINode, BotWS, …).
 *
 * On 32-bit the macros just reinterpret the inline int slot and the side-band
 * tables compile out entirely, reproducing the original memory image exactly.
 * Every gate in botlib.c follows this one predicate. */
#if defined(__x86_64__) || defined(__aarch64__)
#define BOTLIB_NEED_SIDEBAND 1
#else
#define BOTLIB_NEED_SIDEBAND 0
#endif


/* Field-table spelling for the structdef_t descriptors recovered from .data.
 * Shared by be_aas_sound / be_ai_goal / be_ai_weap, which own one table each.
 * A structdef is { int size; char **fields; }; each field entry is 7 (char *)
 * slots: name, byte offset, type flags, array count, 0, default float-bits, 0. */
/* Cast integer constant to char * for mixed pointer/int field table slots */
#define P(x) ((char *)(uintptr_t)(x))

/* One field table entry (7 slots): name, offset, flags, arrcount, 0, default, 0 */
#define FE(name, off, flags, arr, def) \
    (name), P(off), P(flags), P(arr), P(0), P(def), P(0)

/* Null terminator entry */
#define FE_END \
    P(0),  P(0),   P(0),   P(0),  P(0),  P(0),  P(0)


#endif /* BOTLIB_PORT_H */
