/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'gladiator.dll'
*/

#ifndef GLADIATOR_DLL_H
#define GLADIATOR_DLL_H

#include <stddef.h>   /* wchar_t, offsetof, size_t */

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* _iobuf/FILE are provided by <stdio.h> which must be included before this header. */

/* MSVC calling conventions.
 * On non-Windows targets these are no-ops.
 * On MinGW (Windows target, non-MSVC) __cdecl and __stdcall are built-in
 * GCC keywords — do NOT redefine them or the calling-convention attribute is
 * silently discarded, which breaks GetBotAPI (game.dll calls it __stdcall). */
#if !defined(_MSC_VER) && !defined(_WIN32)
#ifndef __cdecl
#define __cdecl
#endif
#ifndef __stdcall
#define __stdcall
#endif
#ifndef __fastcall
#define __fastcall
#endif
#endif

/* Types required by MSVC exception-handling structs below,
   not otherwise defined in this header. */
typedef void *PVOID;
struct _EXCEPTION_RECORD;
struct _CONTEXT;
struct _EXCEPTION_POINTERS {
  struct _EXCEPTION_RECORD *ExceptionRecord;
  struct _CONTEXT           *ContextRecord;
};
typedef struct _EXCEPTION_POINTERS EXCEPTION_POINTERS;

/* 1 */
struct _SCOPETABLE_ENTRY
{
  int EnclosingLevel;
  void *FilterFunc;
  void *HandlerFunc;
};

/* 2 */
typedef struct _SCOPETABLE_ENTRY *PSCOPETABLE_ENTRY;

/* 8 */
typedef unsigned int DWORD;
typedef unsigned int _DWORD;

/* IDA Pro type aliases */
typedef unsigned char  _BYTE;
typedef unsigned short _WORD;
typedef unsigned int   _UNKNOWN;  /* IDA placeholder for unresolved 4-byte types */

/* Windows types not in the standard headers */
typedef void        *HGLOBAL;
typedef void        *HMODULE;
typedef void        *FARPROC;
typedef const char  *LPCSTR;

/* IDA Pro bit-extraction macros.
   These reinterpret the bit pattern of a value at a given byte offset,
   matching what the x86 MSVC compiler emitted for partial-register reads. */
#define LOBYTE(x)    (*(unsigned char *)&(x))
#define HIBYTE(x)    (*((unsigned char *)&(x) + 1))
#define BYTE1(x)     (*((unsigned char *)&(x) + 1))   /* alias for HIBYTE */
#define LOWORD(x)    (*(unsigned short *)&(x))
#define HIWORD(x)    (*((unsigned short *)&(x) + 1))
#define LODWORD(x)   (*(unsigned int *)&(x))
#define HIDWORD(x)   (*((int *)&(x) + 1))            /* signed: needed for IDA's `(HIDWORD(v) ^ v) - HIDWORD(v)` abs idiom on 64-bit */
#define SLODWORD(x)  (*(int *)&(x))                   /* signed variant */
#define SLOBYTE(x)   (*(signed char *)&(x))
#define BYTE2(x)     (*((unsigned char *)&(x) + 2))                   /* signed variant */
/* COERCE_FLOAT: reinterpret an int's bits as a float.
   Implemented as an inline function (union type-punning, C99 §6.5.2.3) so it
   works on rvalues (e.g., function return values) unlike the & form. */
static inline float COERCE_FLOAT(int _x) { union { int i; float f; } _u; _u.i = _x; return _u.f; }

/* 3 */
struct _EH3_EXCEPTION_REGISTRATION
{
  struct _EH3_EXCEPTION_REGISTRATION *Next;
  PVOID ExceptionHandler;
  PSCOPETABLE_ENTRY ScopeTable;
  DWORD TryLevel;
};

/* 4 */
typedef struct _EH3_EXCEPTION_REGISTRATION EH3_EXCEPTION_REGISTRATION;

/* 5 */
typedef struct _EH3_EXCEPTION_REGISTRATION *PEH3_EXCEPTION_REGISTRATION;

/* 6 */
struct CPPEH_RECORD
{
  DWORD old_esp;
  EXCEPTION_POINTERS *exc_ptr;
  struct _EH3_EXCEPTION_REGISTRATION registration;
};

/* 7 */
struct _FILETIME
{
  DWORD dwLowDateTime;
  DWORD dwHighDateTime;
};

/* 11 */
typedef char CHAR;

/* 10 */
typedef CHAR *LPSTR;

/* 12 */
typedef unsigned __int16 WORD;

/* 14 */
typedef unsigned __int8 BYTE;

/* 13 */
typedef BYTE *LPBYTE;

/* 15 */
typedef void *HANDLE;

/* 9 */
struct _STARTUPINFOA
{
  DWORD cb;
  LPSTR lpReserved;
  LPSTR lpDesktop;
  LPSTR lpTitle;
  DWORD dwX;
  DWORD dwY;
  DWORD dwXSize;
  DWORD dwYSize;
  DWORD dwXCountChars;
  DWORD dwYCountChars;
  DWORD dwFillAttribute;
  DWORD dwFlags;
  WORD wShowWindow;
  WORD cbReserved2;
  LPBYTE lpReserved2;
  HANDLE hStdInput;
  HANDLE hStdOutput;
  HANDLE hStdError;
};

/* 17 */
typedef void *LPVOID;

/* 18 */
typedef int BOOL;
typedef int qboolean;  /* Q3-style boolean; matches game/botlib.h `typedef int qboolean` */

/* 16 */
struct _SECURITY_ATTRIBUTES
{
  DWORD nLength;
  LPVOID lpSecurityDescriptor;
  BOOL bInheritHandle;
};

/* 20 */
typedef unsigned int UINT;

/* 19 */
struct _cpinfo
{
  UINT MaxCharSize;
  BYTE DefaultChar[2];
  BYTE LeadByte[12];
};

/* 21 */
struct _OSVERSIONINFOA
{
  DWORD dwOSVersionInfoSize;
  DWORD dwMajorVersion;
  DWORD dwMinorVersion;
  DWORD dwBuildNumber;
  DWORD dwPlatformId;
  CHAR szCSDVersion[128];
};

/* 23 */
typedef int LONG;

/* 25 */
/* wchar_t: defined by <stddef.h> on POSIX as unsigned int (32-bit).
 * Only provide the Windows 16-bit alias on Windows targets. */
#if defined(_WIN32) && !defined(__cplusplus)
typedef unsigned __int16 wchar_t;
#endif

/* 24 */
typedef wchar_t WCHAR;

/* 27 */
struct _SYSTEMTIME
{
  WORD wYear;
  WORD wMonth;
  WORD wDayOfWeek;
  WORD wDay;
  WORD wHour;
  WORD wMinute;
  WORD wSecond;
  WORD wMilliseconds;
};

/* 26 */
typedef struct _SYSTEMTIME SYSTEMTIME;

/* 22 */
struct _TIME_ZONE_INFORMATION
{
  LONG Bias;
  WCHAR StandardName[32];
  SYSTEMTIME StandardDate;
  LONG StandardBias;
  WCHAR DaylightName[32];
  SYSTEMTIME DaylightDate;
  LONG DaylightBias;
};

/* 28 */
struct _PROCESS_INFORMATION
{
  HANDLE hProcess;
  HANDLE hThread;
  DWORD dwProcessId;
  DWORD dwThreadId;
};

/* 29, 30 — _iobuf/FILE: provided by <stdio.h>, included before this header. */

/* vec3_t — 3-component float vector, matches Q3/Q2 definition.
 * Guarded: game/botlib.h (BOTLIB_H) and q_shared.h (Q_SHARED_H) both define it. */
#if !defined(BOTLIB_H) && !defined(Q_SHARED_H)
typedef float vec3_t[3];
#endif

/* Q2 BSP file header (AAS_LoadBSPFile, 0xA0 = 160 bytes).
 * Matches dheader_t from Quake 2 source qfiles.h.
 * Original: `lea eax,[esp+0x18]; push 0xa0; push eax; call fread_locked`
 * then fields at [esp+0x10]=ident, [esp+0x14]=version, [esp+0x18]=lumps[0]... */
typedef struct { int fileofs; int filelen; } bsp_lump_t;
typedef struct {
    int       ident;            /* "IBSP" = 0x50534249   */
    int       version;          /* 38 for Q2 BSP         */
    bsp_lump_t lumps[19];       /* 19 lumps × 8 = 152 B  */
} dBspHeader_t;                 /* sizeof = 160 = 0xA0   */

/* Gladiator AAS file header (AAS_LoadAASFile, 0x78 = 120 bytes).
 * Q3's aas_header_t adds a bspchecksum field (0x7C=124); Gladiator omits it.
 * Same lump layout as Q3 but 14 lumps instead of Q3's 14+checksum variant. */
typedef struct { int fileofs; int filelen; } aas_lump_t;
#define AAS_LUMPS_Q2 14
typedef struct {
    int         ident;              /* "EAAS" = 0x53414145     */
    int         version;            /* 2 = old, 3 = current    */
    aas_lump_t  lumps[AAS_LUMPS_Q2];/* 14 lumps × 8 = 112 B   */
} aas_header_t;                     /* sizeof = 120 = 0x78     */

/* bsp_surface_t, bot_settings_t, bot_clientsettings_t — defined in game/botlib.h. */

/* bot_fileref_t — file location returned by sub_10041F60 / sub_10041BA0.
 * Size = 4 + 4 + MAX_FILEPATH = 4 + 4 + 144 = 152 bytes = 38 ints.
 * IDA represents this as "int Offset[38]" in functions where it can't resolve the type,
 * or decomposes it into three separate locals (int Offset + size_t ElementSize +
 * char Source[144]) in others — both are the same struct.  The field names match
 * Q2 pak-file terminology (fileofs/filelen are standard Quake2 .pak lump terms).
 * MAX_FILEPATH = 144 is defined in gladq2_src/botlib.h.
 * Not present in Q3 botlib — Q3 uses a transparent VFS (FS_FOpenFileRead) that
 * handles pak files internally, so this struct is Q2-specific. */
typedef struct bot_fileref_s {
    int  fileofs;              /* file offset within pak  (0 = file is directly on disk)  */
    int  filelen;              /* file length within pak  (0 = read whole file from disk)  */
    char path[144];            /* path to pak file, or direct file path when fileofs == 0  */
                               /* 144 = MAX_FILEPATH from gladq2_src/botlib.h               */
} bot_fileref_t;               /* sizeof = 152 bytes = 38 ints ("int Offset[38]" in IDA)   */

/* scriptcrc_s — 152-byte record in the dword_10063F2C linked list.
 * Allocated by GetClearedMemory(152) in sub_100376B0.  Each record
 * memorises a (filename, CRC-hash) pair so the engine can warn when a
 * script's CRC differs from one previously seen.  Q3 botlib has no
 * direct analogue (its CRC table is keyed differently); name chosen
 * descriptively.  Field offsets exactly match the 32-bit binary. */
typedef struct scriptcrc_s {
    __int16              hash;            /* +0   CRC-16 of the file body  */
    char                 name[146];       /* +2   filename (zero-terminated) */
    struct scriptcrc_s  *next;            /* +148 on 32-bit; offset moves to +152 on 64-bit */
} scriptcrc_t;                            /* sizeof = 152 on 32-bit, 160 on 64-bit */

/* structdef_t — struct descriptor passed to ReadStructure / FindField.
 * In the original 32-bit DLL this was a plain int[2] array { size, fields_ptr }.
 * Using a proper struct makes it pointer-size-agnostic (works on both 32 and 64-bit). */
typedef struct { int size; char **fields; } structdef_t;

/* token_t — script token (= Q3A l_script.h::token_t with NUMBERVALUE).
 * Layout verified by disassembly of gladiator.dll (PS_ReadToken writes):
 *   type        at buf+256*4 = +0x400 ✓
 *   linescrossed at buf+265*4 = +0x424 ✓   → next at +0x428
 * Q3 comparison: Q3 has float floatvalue (+0x40C, 4 bytes) giving next at +0x420.
 * Gladiator has double floatvalue (+0x410, 8 bytes) with 4-byte alignment pad before it,
 * which pushes whitespace_p to +0x418 and next to +0x428 — matching disassembly. */
typedef struct token_s {
    char string[1024];                   /* +0x000: token text (MAX_TOKEN chars)     */
    int type;                            /* +0x400: TT_STRING=1 NUMBER=3 NAME=4 PUNCT=5 */
    int subtype;                         /* +0x404: punctuation id / number subtype  */
    unsigned int intvalue;               /* +0x408: integer value.  Original was
                                          *         `unsigned long` in 32-bit MSVC =
                                          *         4 bytes; kept 4 bytes here so the
                                          *         offsets through +0x420 stay
                                          *         binary-identical with the original. */
    int _floatvalue_pad;                 /* +0x40C: alignment padding before double  */
    double floatvalue;                   /* +0x410: floating-point value (8 bytes)   */
    char *whitespace_p;                  /* +0x418 on 32-bit (grows to +0x418 still
                                          *         on 64-bit; pointer width doubles) */
    char *endwhitespace_p;
    int line;
    int linescrossed;
    struct token_s *next;
    int padding;
} token_t;
/* Original gladiator DLL was 32-bit, so token_t was 0x430 (1072) bytes.
 * On 64-bit the three pointer fields (whitespace_p, endwhitespace_p, next)
 * grow to 8 bytes each, so the struct expands to 1088 bytes.  All copy/
 * alloc sites that used the literal constant 1072 / 0x430 must therefore
 * be migrated to sizeof(token_t).  Fields up through `floatvalue` keep
 * their original 32-bit offsets, which is all we can guarantee. */

/* ========================================================================
 * aas_soundpool_t — node of the AAS active-sound bookkeeping pool.
 *
 * Original gladiator allocated `52 * MAX_AAS_SOUNDS` raw bytes from
 * GetMemory and treated it as a packed array of 52-byte nodes.  Each
 * node had a doubly-linked-list pair (prev,next) at offsets +44/+48,
 * with the leading 44 bytes carrying payload — at minimum a float at
 * offset +4 (sort key, see sub_1001CC50).  The remaining payload bytes
 * have not yet been identified; they are preserved opaquely as
 * `data[44]` so the on-disk 32-bit layout is byte-identical and field
 * accesses at +44 / +48 become proper struct-pointer accesses on 64-bit
 * (where the pool node grows from 52 to 64 bytes).
 *
 * Six aas_world fields reference these nodes:
 *   d_100669C4 = pool base (FreeMemory'd in sub_1001CAB0)
 *   d_100669C8 = free-list head, chained via .next
 *   d_100669CC/D0 = head/tail of one sorted active list
 *   d_100669D4/D8 = head/tail of a second sorted active list
 * ======================================================================== */
typedef struct aas_soundpool_s {
    char                       data[44]; /* opaque payload (incl. float sort key @+4) */
    struct aas_soundpool_s    *prev;     /* +44 on 32-bit; struct padding pushes to +48 on 64-bit */
    struct aas_soundpool_s    *next;
} aas_soundpool_t;

/* bot_import_t, bot_export_t — defined in game/botlib.h (properly typed).
 * Include game/botlib.h before this header to get these definitions. */

/* ========================================================================
 * aas_world_t — Area Awareness System global state.
 *
 * In the original Gladiator DLL, this is one contiguous 676-byte (0x2A4)
 * struct in BSS starting at VA 0x100667E0. IDA decomposed every field into
 * a separate global, which broke the `memset(&aasworld_loaded, 0, 0x2A4u)`
 * call in AAS_Shutdown — under GCC the linker doesn't pack BSS globals in
 * declaration order, so the memset would corrupt unrelated globals.
 *
 * Field offsets verified against original binary (0x100667E0..0x10066A84).
 * Each field's binary VA is shown alongside the struct offset.  The matching
 * `aasworld_*` legacy names are restored as #define macros in the .c file.
 * ======================================================================== */
/* Forward decl needed for aas_world_s::entities (defined in aas_world.h) */
struct aas_entity_s;
typedef struct aas_entity_s aas_entity_t;

/* Routing structures whose pointer slots truncated when typed as plain
 * `int` in the IDA decompile.  Restored with real pointer fields so the
 * heap layout is 64-bit-safe.  Stride is computed via sizeof(...) at the
 * use sites (instead of the hard-coded 40 / 8 / 12 constants from the
 * 32-bit binary), keeping behaviour identical on 32-bit Windows. */
typedef struct aas_reversedlink_s {
    int                         linknum;     /* +0  reachability index        */
    int                         areanum;     /* +4  source area for the link  */
    struct aas_reversedlink_s  *next;        /* +8  next link for this area   */
} aas_reversedlink_t;

typedef struct {
    int                         numlinks;    /* +0  links into this area      */
    aas_reversedlink_t         *first;       /* +4  head of link chain        */
} aas_reversedreach_t;

typedef struct aas_routingupdate_s {
    int                            cluster;          /* +0  origin cluster (portal updates) */
    int                            areanum;          /* +4  area being updated     */
    float                          start[3];         /* +8  origin                 */
    unsigned short                 tmptraveltime;    /* +20 best traveltime so far */
    unsigned short                 pad22;            /* +22 alignment              */
    unsigned short                *areatraveltimes;  /* +24 inner traveltime row   */
    int                            inlist;           /* +28 1 = queued             */
    struct aas_routingupdate_s    *next;             /* +32 fifo next              */
    struct aas_routingupdate_s    *prev;             /* +36 fifo prev              */
} aas_routingupdate_t;
typedef struct aas_world_s {
    int   loaded;                   /* +0x000  (VA 0x100667E0) */
    int   initialized;              /* +0x004  (VA 0x100667E4) */
    int   savefile;                 /* +0x008  (VA 0x100667E8) */
    float time;                     /* +0x00C  (VA 0x100667EC, was global "aastime")    */
    char  filename[144];            /* +0x010  (VA 0x100667F0) */
    char  mapname[144];             /* +0x0A0  (VA 0x10066880) */
    int   numbboxes;                /* +0x130  (VA 0x10066910) */
    void *bboxes;                   /* +0x134  (VA 0x10066914, was "Buffer")            */
    int   numvertexes;              /* +0x138 */
    void *vertexes;                 /* +0x13C */
    int   numplanes;                /* +0x140 */
    void *planes;                   /* +0x144 */
    int   numedges;                 /* +0x148 */
    void *edges;                    /* +0x14C */
    int   edgeindexsize;            /* +0x150 */
    void *edgeindex;                /* +0x154 */
    int   numfaces;                 /* +0x158 */
    void *faces;                    /* +0x15C */
    int   faceindexsize;            /* +0x160 */
    void *faceindex;                /* +0x164 */
    int   numareas;                 /* +0x168 */
    void *areas;                    /* +0x16C */
    int   numareasettings;          /* +0x170 */
    void *areasettings;             /* +0x174 */
    int   reachabilitysize;         /* +0x178 */
    void *reachability;             /* +0x17C */
    int   numnodes;                 /* +0x180 */
    void *nodes;                    /* +0x184 */
    int   numportals;               /* +0x188  (VA 0x10066968, was "dword_10066968")    */
    void *portals;                  /* +0x18C */
    int   portalindexsize;          /* +0x190 */
    void *portalindex;              /* +0x194 */
    int   numclusters;              /* +0x198  (VA 0x10066978, was "ArgList")           */
    void *clusters;                 /* +0x19C */
    int   numreachabilityareas;     /* +0x1A0  (VA 0x10066980) */
    float reachabilitytime;         /* +0x1A4  (Q3-equivalent slot; binary leaves 4 B)  */
    struct aas_link_s  *linkheap;   /* +0x1A8  (VA 0x10066988) */
    int   linkheapsize;             /* +0x1AC */
    struct aas_link_s  *freelinks;  /* +0x1B0 */
    struct aas_link_s **arealinkedentities; /* +0x1B4 */
    int   numentities;              /* +0x1B8 */
    int   maxclients;               /* +0x1BC */
    aas_entity_t *entities;         /* +0x1C0  (pointer; 32-bit binary stored as int) */
    struct indexlist_s *modelindex_table;  /* +0x1C4  (VA 0x100669A4) */
    struct indexlist_s *soundindex_table;  /* +0x1C8 */
    struct indexlist_s *imageindex_table;  /* +0x1CC */
    int   indexes_loaded;           /* +0x1D0 */
    int   numsoundinfo;             /* +0x1D4  (VA 0x100669B4) sound entry count        */
    void *soundinfo;                /* +0x1D8  (VA 0x100669B8) soundinfo_t array        */
    int    d_100669BC;              /* +0x1DC */
    void **d_100669C0;              /* +0x1E0  per-soundindex pointers into soundinfo[] */
    /* aas_world.d_100669C4..D8 are six pointers maintaining a 52-byte
     * pool of `aas_soundpool_t` nodes (allocated by sub_1001CAB0):
     *   d_100669C4 = pool base (raw GetMemory return)
     *   d_100669C8 = free-list head (chained via next at +48)
     *   d_100669CC, d_100669D0 = head/tail of sorted active list #1
     *   d_100669D4, d_100669D8 = head/tail of sorted active list #2
     * Original DLL stored these as `int` because pointers were 32-bit;
     * on 64-bit they MUST be real pointer types or every list walk
     * truncates.  Bound type-wise to aas_soundpool_t which is restored
     * below. */
    struct aas_soundpool_s *d_100669C4;  /* +0x1E4 */
    struct aas_soundpool_s *d_100669C8;  /* +0x1E8 */
    struct aas_soundpool_s *d_100669CC;  /* +0x1EC */
    struct aas_soundpool_s *d_100669D0;  /* +0x1F0 */
    struct aas_soundpool_s *d_100669D4;  /* +0x1F4 */
    struct aas_soundpool_s *d_100669D8;  /* +0x1F8 */
    int   _pad_1FC;                 /* +0x1FC  (4-byte gap; binary leaves slot empty)   */
    struct bsp_pointlight_s *oldestcache;  /* +0x200  (VA 0x100669E0) — point-light free pool head */
    struct bsp_pointlight_s *newestcache;  /* +0x204                  — point-light live list head */
    int   travelflagfortype[32];    /* +0x208  (VA 0x100669E8, 128 bytes)               */
    aas_routingupdate_t *areaupdate;     /* +0x288  (VA 0x10066A68) */
    aas_routingupdate_t *portalupdate;   /* +0x28C */
    int   frameroutingupdates;      /* +0x290 */
    aas_reversedreach_t *reversedreachability; /* +0x294 */
    unsigned short ***areatraveltimes; /* +0x298 [area][reachidx][2*linkidx] */
    struct aas_routingcache_s ***clusterareacache; /* +0x29C [cluster][areaInCluster] */
    struct aas_routingcache_s **portalcache;       /* +0x2A0 [area]                   */
} aas_world_t;                      /* sizeof == 0x2A4 == 676                           */

/* Compile-time offset checks vs the original binary's VA layout (must run
 * BEFORE the macro definitions below — some legacy names like
 * `modelindex_table` collide with struct field names).
 * These checks are only valid on 32-bit builds (Windows/MinGW): the struct
 * contains void* pointers which are 4 bytes on 32-bit and 8 bytes on 64-bit,
 * so the offsets beyond the first pointer field shift on 64-bit Linux. */
#include <stddef.h>  /* offsetof */
#if __SIZEOF_POINTER__ == 4
_Static_assert(sizeof(aas_world_t) == 0x2A4,                     "aas_world_t size");
_Static_assert(offsetof(aas_world_t, loaded)               == 0x000, "loaded");
_Static_assert(offsetof(aas_world_t, time)                 == 0x00C, "time");
_Static_assert(offsetof(aas_world_t, filename)             == 0x010, "filename");
_Static_assert(offsetof(aas_world_t, mapname)              == 0x0A0, "mapname");
_Static_assert(offsetof(aas_world_t, numbboxes)            == 0x130, "numbboxes");
_Static_assert(offsetof(aas_world_t, numportals)           == 0x188, "numportals");
_Static_assert(offsetof(aas_world_t, numclusters)          == 0x198, "numclusters");
_Static_assert(offsetof(aas_world_t, numreachabilityareas) == 0x1A0, "numreachabilityareas");
_Static_assert(offsetof(aas_world_t, linkheap)             == 0x1A8, "linkheap");
_Static_assert(offsetof(aas_world_t, modelindex_table)     == 0x1C4, "modelindex_table");
_Static_assert(offsetof(aas_world_t, oldestcache)          == 0x200, "oldestcache");
_Static_assert(offsetof(aas_world_t, travelflagfortype)    == 0x208, "travelflagfortype");
_Static_assert(offsetof(aas_world_t, areaupdate)           == 0x288, "areaupdate");
_Static_assert(offsetof(aas_world_t, portalcache)          == 0x2A0, "portalcache");
#endif /* __SIZEOF_POINTER__ == 4 */

/* Single instance defined in gladiator_deobfuscated.c. */
extern aas_world_t aasworld;

#endif /* GLADIATOR_DLL_H */

